-- =============================================================================
-- Rollback for: 001_task_board_schema.sql  (Option A — ALTER TABLE additive)
-- =============================================================================
-- 🛑 PRIMARY ROLLBACK STRATEGY = frontend feature flag
--
-- Per project rule: "ห้าม DROP TABLE ทุกกรณี"
-- Per project rule: "ห้าม DROP COLUMN ทุกกรณี" (implied by additive-only rule)
-- → DO NOT execute hard rollback unless user explicitly approves.
--
-- The SAFE rollback path is:
--   1. In index.html, set `USE_TASK_API = false`
--   2. Frontend reverts to saveAll() + workspace_snapshot (the path it always used)
--   3. The new columns (version, deleted_at, created_by) sit unused on tasks
--   4. The new tables (task_checklists, task_comments) sit empty
--   5. workspace_snapshot.data->'tasks' was never touched — source of truth intact
--
-- =============================================================================
-- HARD ROLLBACK (commented out — requires separate "ยืนยัน รันได้เลย" approval)
-- =============================================================================
-- Only run during a planned maintenance window after confirming:
--   - USE_TASK_API = false on all clients for at least 24h
--   - workspace_snapshot.data->'tasks' has the latest authoritative data
--   - A pg_dump backup has been taken
--
-- BEGIN;
--   -- Drop the version-bump trigger + function we added
--   DROP TRIGGER IF EXISTS trigger_tasks_bump_version ON tasks;
--   DROP FUNCTION IF EXISTS tasks_bump_version();
--
--   -- Drop indexes we added
--   DROP INDEX IF EXISTS idx_tasks_workspace_updated;
--   DROP INDEX IF EXISTS idx_tasks_workspace_active;
--
--   -- Drop columns we added to existing tasks table
--   ALTER TABLE tasks DROP COLUMN IF EXISTS created_by;
--   ALTER TABLE tasks DROP COLUMN IF EXISTS deleted_at;
--   ALTER TABLE tasks DROP COLUMN IF EXISTS version;
--
--   -- Drop net-new tables we created
--   DROP TABLE IF EXISTS task_comments;
--   DROP TABLE IF EXISTS task_checklists;
-- COMMIT;
--
-- ⚠️ ABOVE SQL IS INTENTIONALLY COMMENTED. DO NOT UNCOMMENT WITHOUT APPROVAL.
